#!/bin/bash

#!/bin/bash
#
# Bash script to serve as a wrapper for busybox netcat (nc) setup the server 
# running the AMS software and listen for incoming client connections
#
# Usage:
#   ./run_server server_port
#
# Evan Chodora (AF5E), 2019
# https://github.com/evanchodora/radio_ams

# Check to ensure busybox is available
if ! [ -x "$(command -v ./busybox)" ]; then
        echo 'Error: busybox (nc) is missing'
        echo 'See REAMDE.md for more information'
        exit 1
fi

# Script usage help line
usage() { 
echo "Wrapper for busybox nc that run the server program"
echo "Usage: $0 server_port [-h | --help]"
echo "See README.md for more information." 1>&2; }

# Check for proper flags for help
while getopts ":h" o; do
	case "${o}" in
		h)
			usage
			exit 0
			;;
		*)
			usage
			exit 1
			;;
	esac
done
shift $((OPTIND-1))

# Check if three arguments were passed to the script
if [ $# -lt 1 ]; then
        echo "Missing required server port parameter"
        echo "$0 --help for more information"
        exit 1
fi

# Store variables
port=$1

# Run the server connection up client connection
server_program=./server.sh

./busybox nc -vlk -p $port -e $server_program
